"""Adiciona saldo_devedor a financiamento_parcela

Revision ID: 150940ad07bf
Revises: 5bb825ece7df
Create Date: 2025-08-03 18:56:12.523459

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '150940ad07bf'
down_revision = '5bb825ece7df'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('financiamento_parcela', schema=None) as batch_op:
        batch_op.add_column(sa.Column('saldo_devedor', sa.Numeric(precision=12, scale=2), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('financiamento_parcela', schema=None) as batch_op:
        batch_op.drop_column('saldo_devedor')

    # ### end Alembic commands ###
