"""Integração dos modelos de Financiamento

Revision ID: 2400381658f3
Revises: a249166f1eee
Create Date: 2025-08-01 18:06:11.137035

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2400381658f3'
down_revision = 'a249166f1eee'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('financiamento',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('conta_id', sa.Integer(), nullable=False),
    sa.Column('nome_financiamento', sa.String(length=100), nullable=False),
    sa.Column('valor_total_financiado', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('saldo_devedor_atual', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('taxa_juros_anual', sa.Numeric(precision=5, scale=4), nullable=False),
    sa.Column('data_inicio', sa.Date(), nullable=False),
    sa.Column('prazo_meses', sa.Integer(), nullable=False),
    sa.Column('tipo_amortizacao', sa.Enum('SAC', 'PRICE', 'Outro', name='tipo_amortizacao_enum'), nullable=False),
    sa.Column('data_criacao', sa.DateTime(), nullable=False),
    sa.Column('descricao', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['conta_id'], ['conta.id'], ),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuario.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('usuario_id', 'nome_financiamento', name='_usuario_financiamento_uc')
    )
    op.create_table('financiamento_parcela',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('financiamento_id', sa.Integer(), nullable=False),
    sa.Column('numero_parcela', sa.Integer(), nullable=False),
    sa.Column('valor_principal', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('valor_juros', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('valor_seguro', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('valor_taxas', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('valor_total_previsto', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('data_vencimento', sa.Date(), nullable=False),
    sa.Column('pago', sa.Boolean(), nullable=False),
    sa.Column('data_pagamento', sa.Date(), nullable=True),
    sa.Column('movimento_bancario_id', sa.Integer(), nullable=True),
    sa.Column('data_criacao', sa.DateTime(), nullable=False),
    sa.Column('status', sa.Enum('A Pagar', 'Paga', 'Atrasada', 'Amortizada', name='status_parcela_enum'), nullable=False),
    sa.Column('observacoes', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['financiamento_id'], ['financiamento.id'], ),
    sa.ForeignKeyConstraint(['movimento_bancario_id'], ['conta_movimento.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('financiamento_id', 'numero_parcela', name='_financiamento_parcela_uc')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('financiamento_parcela')
    op.drop_table('financiamento')
    # ### end Alembic commands ###
