"""Cria tabela conta_transacao para tipos de transação bancária

Revision ID: 24f2f0eecda7
Revises: d6dcd39ad411
Create Date: 2025-07-27 00:17:21.885919

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '24f2f0eecda7'
down_revision = 'd6dcd39ad411'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('conta_transacao',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('transacao_tipo', sa.String(length=100), nullable=False),
    sa.Column('tipo', sa.Enum('Crédito', 'Débito', name='tipo_movimento_enum'), nullable=False),
    sa.Column('data_criacao', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuario.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('usuario_id', 'transacao_tipo', 'tipo', name='_usuario_transacao_tipo_uc')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('conta_transacao')
    # ### end Alembic commands ###
