"""Adiciona multa e mora a financiamento_parcela

Revision ID: 40e590a0645f
Revises: 150940ad07bf
Create Date: 2025-08-03 19:16:53.351670

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '40e590a0645f'
down_revision = '150940ad07bf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('financiamento_parcela', schema=None) as batch_op:
        batch_op.add_column(sa.Column('multa', sa.Numeric(precision=12, scale=2), nullable=False))
        batch_op.add_column(sa.Column('mora', sa.Numeric(precision=12, scale=2), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('financiamento_parcela', schema=None) as batch_op:
        batch_op.drop_column('mora')
        batch_op.drop_column('multa')

    # ### end Alembic commands ###
