"""Adiciona login_criado a solicitacao_acesso

Revision ID: 46176b578268
Revises: ba5e766e53db
Create Date: 2025-08-17 19:32:45.436933

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '46176b578268'
down_revision = 'ba5e766e53db'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('solicitacao_acesso', schema=None) as batch_op:
        batch_op.add_column(sa.Column('login_criado', sa.String(length=80), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('solicitacao_acesso', schema=None) as batch_op:
        batch_op.drop_column('login_criado')

    # ### end Alembic commands ###
