"""Adiciona campo destino ao crediario_movimento

Revision ID: 5557c419c4ab
Revises: 1045cb2dd0b5
Create Date: 2025-10-10 12:08:52.460282

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5557c419c4ab'
down_revision = '1045cb2dd0b5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('crediario_movimento', schema=None) as batch_op:
        batch_op.add_column(sa.Column('destino', sa.Enum('Próprio', 'Outros', 'Coletivo', name='destino_crediario_enum'), server_default='Próprio', nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('crediario_movimento', schema=None) as batch_op:
        batch_op.drop_column('destino')

    # ### end Alembic commands ###
