"""Adiciona tabelas de Despesas e Receitas ao BD

Revision ID: 5e79fce8de0a
Revises: 40e590a0645f
Create Date: 2025-08-04 14:35:23.250486

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5e79fce8de0a'
down_revision = '40e590a0645f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('desp_rec',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=100), nullable=False),
    sa.Column('natureza', sa.Enum('Receita', 'Despesa', name='natureza_enum'), nullable=False),
    sa.Column('tipo', sa.Enum('Variável', 'Fixa', name='tipo_desp_rec_enum'), nullable=False),
    sa.Column('dia_vencimento', sa.Integer(), nullable=True),
    sa.Column('ativo', sa.Boolean(), nullable=False),
    sa.Column('data_criacao', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuario.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('usuario_id', 'nome', 'natureza', 'tipo', name='_usuario_desp_rec_uc')
    )
    op.create_table('desp_rec_movimento',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('desp_rec_id', sa.Integer(), nullable=False),
    sa.Column('data_vencimento', sa.Date(), nullable=False),
    sa.Column('valor_previsto', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('data_pagamento', sa.Date(), nullable=True),
    sa.Column('valor_realizado', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('status', sa.Enum('Pendente', 'Pago', 'Atrasado', name='status_lancamento_enum'), nullable=False),
    sa.Column('descricao', sa.String(length=255), nullable=True),
    sa.Column('movimento_bancario_id', sa.Integer(), nullable=True),
    sa.Column('data_criacao', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['desp_rec_id'], ['desp_rec.id'], ),
    sa.ForeignKeyConstraint(['movimento_bancario_id'], ['conta_movimento.id'], ),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuario.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('desp_rec_movimento')
    op.drop_table('desp_rec')
    # ### end Alembic commands ###
