"""Cria tabela conta_movimento para movimentações bancárias

Revision ID: 6079d7f9ec87
Revises: 24f2f0eecda7
Create Date: 2025-07-27 16:35:59.160988

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6079d7f9ec87'
down_revision = '24f2f0eecda7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('conta_movimento',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('conta_id', sa.Integer(), nullable=False),
    sa.Column('conta_transacao_id', sa.Integer(), nullable=False),
    sa.Column('data_movimento', sa.Date(), nullable=False),
    sa.Column('valor', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('descricao', sa.String(length=255), nullable=True),
    sa.Column('id_movimento_relacionado', sa.Integer(), nullable=True),
    sa.Column('data_criacao', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['conta_id'], ['conta.id'], ),
    sa.ForeignKeyConstraint(['conta_transacao_id'], ['conta_transacao.id'], ),
    sa.ForeignKeyConstraint(['id_movimento_relacionado'], ['conta_movimento.id'], ),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuario.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('conta_movimento')
    # ### end Alembic commands ###
