"""Adiciona link de pagamento a fatura de crediario

Revision ID: 8448346d913e
Revises: f99e1ba456ac
Create Date: 2025-08-09 09:48:38.053292

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8448346d913e'
down_revision = 'f99e1ba456ac'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('crediario_fatura', schema=None) as batch_op:
        batch_op.add_column(sa.Column('movimento_bancario_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'conta_movimento', ['movimento_bancario_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('crediario_fatura', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('movimento_bancario_id')

    # ### end Alembic commands ###
