"""Cria tabelas para crediarios, grupos, movimentos e parcelas

Revision ID: 8c4e2d612bde
Revises: 86433f1dc4cc
Create Date: 2025-07-30 16:42:29.479228

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8c4e2d612bde'
down_revision = '86433f1dc4cc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('crediario',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('nome_crediario', sa.String(length=100), nullable=False),
    sa.Column('tipo_crediario', sa.Enum('Cartão Físico', 'Cartão VR', 'Cartão VT', 'Boleto', 'Cheque', 'Outro', name='tipo_crediario_enum'), nullable=False),
    sa.Column('identificador_final', sa.String(length=50), nullable=True),
    sa.Column('limite_total', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('ativa', sa.Boolean(), nullable=False),
    sa.Column('data_criacao', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuario.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('usuario_id', 'nome_crediario', 'tipo_crediario', 'identificador_final', name='_usuario_crediario_uc')
    )
    op.create_table('crediario_grupo',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('grupo_crediario', sa.String(length=100), nullable=False),
    sa.Column('tipo_grupo_crediario', sa.Enum('Compra', 'Estorno', 'Ajuste', name='tipo_grupo_crediario_enum'), nullable=False),
    sa.Column('data_criacao', sa.DateTime(), nullable=False),
    sa.Column('descricao', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuario.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('usuario_id', 'grupo_crediario', 'tipo_grupo_crediario', name='_usuario_grupo_crediario_uc')
    )
    op.create_table('crediario_movimento',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('crediario_id', sa.Integer(), nullable=False),
    sa.Column('crediario_grupo_id', sa.Integer(), nullable=True),
    sa.Column('data_compra', sa.Date(), nullable=False),
    sa.Column('valor_total_compra', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('descricao', sa.String(length=255), nullable=False),
    sa.Column('numero_parcelas', sa.Integer(), nullable=False),
    sa.Column('data_criacao', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['crediario_grupo_id'], ['crediario_grupo.id'], ),
    sa.ForeignKeyConstraint(['crediario_id'], ['crediario.id'], ),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuario.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('crediario_parcela',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('crediario_movimento_id', sa.Integer(), nullable=False),
    sa.Column('numero_parcela', sa.Integer(), nullable=False),
    sa.Column('data_vencimento', sa.Date(), nullable=False),
    sa.Column('valor_parcela', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('pago', sa.Boolean(), nullable=False),
    sa.Column('data_pagamento', sa.Date(), nullable=True),
    sa.Column('data_criacao', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['crediario_movimento_id'], ['crediario_movimento.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('crediario_movimento_id', 'numero_parcela', name='_crediario_parcela_uc')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('crediario_parcela')
    op.drop_table('crediario_movimento')
    op.drop_table('crediario_grupo')
    op.drop_table('crediario')
    # ### end Alembic commands ###
