"""Adiciona coluna saldo_operacional à Conta

Revision ID: 8d82334cd5bd
Revises: c015c55deef6
Create Date: 2025-12-04 23:04:15.050168

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8d82334cd5bd'
down_revision = 'c015c55deef6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('conta', schema=None) as batch_op:
        batch_op.add_column(sa.Column('saldo_operacional', sa.Boolean(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('conta', schema=None) as batch_op:
        batch_op.drop_column('saldo_operacional')

    # ### end Alembic commands ###
