"""Adiciona campo de motivo para solicitacao de acesso

Revision ID: ba5e766e53db
Revises: e5ac8cead4b1
Create Date: 2025-08-17 15:49:08.702883

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ba5e766e53db'
down_revision = 'e5ac8cead4b1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('solicitacao_acesso', schema=None) as batch_op:
        batch_op.add_column(sa.Column('motivo_decisao', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('solicitacao_acesso', schema=None) as batch_op:
        batch_op.drop_column('motivo_decisao')

    # ### end Alembic commands ###
