"""Cria as tabelas para a funcionalidade de Salário

Revision ID: be8d244e7fab
Revises: d9ecd7d2c0bd
Create Date: 2025-08-05 22:56:38.614587

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'be8d244e7fab'
down_revision = 'd9ecd7d2c0bd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('salario_item',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=100), nullable=False),
    sa.Column('tipo', sa.Enum('Provento', 'Benefício', 'Imposto', 'Desconto', name='tipo_salario_item_enum'), nullable=False),
    sa.Column('ativo', sa.Boolean(), nullable=False),
    sa.Column('descricao', sa.String(length=255), nullable=True),
    sa.Column('data_criacao', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuario.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('usuario_id', 'nome', 'tipo', name='_usuario_salario_item_uc')
    )
    op.create_table('salario_movimento',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('mes_referencia', sa.String(length=7), nullable=False),
    sa.Column('data_recebimento', sa.Date(), nullable=False),
    sa.Column('movimento_bancario_id', sa.Integer(), nullable=True),
    sa.Column('data_criacao', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['movimento_bancario_id'], ['conta_movimento.id'], ),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuario.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('usuario_id', 'mes_referencia', name='_usuario_mes_referencia_uc')
    )
    op.create_table('salario_movimento_item',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('salario_movimento_id', sa.Integer(), nullable=False),
    sa.Column('salario_item_id', sa.Integer(), nullable=False),
    sa.Column('valor', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.ForeignKeyConstraint(['salario_item_id'], ['salario_item.id'], ),
    sa.ForeignKeyConstraint(['salario_movimento_id'], ['salario_movimento.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('salario_movimento_item')
    op.drop_table('salario_movimento')
    op.drop_table('salario_item')
    # ### end Alembic commands ###
