"""Add tipo column to SalarioMovimento and update constraints

Revision ID: c015c55deef6
Revises: 4f32db265bec
Create Date: 2025-11-27 21:05:15.454279

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "c015c55deef6"
down_revision = "4f32db265bec"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("salario_movimento", schema=None) as batch_op:
        # 1. Adiciona a nova coluna
        batch_op.add_column(
            sa.Column(
                "tipo",
                sa.Enum(
                    "Mensal",
                    "Rescisão",
                    "13° Salário",
                    "Férias",
                    "PLR",
                    name="tipo_folha_enum",
                ),
                server_default="Mensal",
                nullable=False,
            )
        )

        # 2. Remove a constraint antiga (usando batch_op)
        # Nota: Não precisa passar o nome da tabela ('salario_movimento') aqui dentro
        batch_op.drop_constraint("_usuario_mes_referencia_uc", type_="unique")

        # 3. Cria a nova constraint (usando batch_op)
        batch_op.create_unique_constraint(
            "_usuario_mes_tipo_uc", ["usuario_id", "mes_referencia", "tipo"]
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("salario_movimento", schema=None) as batch_op:
        batch_op.drop_constraint("_usuario_mes_tipo_uc", type_="unique")
        batch_op.create_index(
            batch_op.f("_usuario_mes_referencia_uc"),
            ["usuario_id", "mes_referencia"],
            unique=True,
        )
        batch_op.drop_column("tipo")

    # ### end Alembic commands ###
