"""Cria tabela conta para contas bancárias

Revision ID: d6dcd39ad411
Revises: f0357f836b81
Create Date: 2025-07-26 22:35:37.663162

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd6dcd39ad411'
down_revision = 'f0357f836b81'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('conta',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('nome_banco', sa.String(length=100), nullable=False),
    sa.Column('agencia', sa.String(length=20), nullable=False),
    sa.Column('conta', sa.String(length=50), nullable=False),
    sa.Column('tipo', sa.Enum('Corrente', 'Poupança', 'Digital', 'Investimento', 'Caixinha', 'Dinheiro', name='tipo_conta_enum'), nullable=False),
    sa.Column('saldo_inicial', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('limite', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('ativa', sa.Boolean(), nullable=False),
    sa.Column('data_criacao', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuario.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('usuario_id', 'nome_banco', 'agencia', 'conta', 'tipo', name='_usuario_conta_uc')
    )
    with op.batch_alter_table('usuario', schema=None) as batch_op:
        batch_op.alter_column('sobrenome',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usuario', schema=None) as batch_op:
        batch_op.alter_column('sobrenome',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)

    op.drop_table('conta')
    # ### end Alembic commands ###
