"""Altera solicitacao_acesso para nome e sobrenome

Revision ID: e5ac8cead4b1
Revises: f047ca1e2c74
Create Date: 2025-08-17 11:48:17.977725

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e5ac8cead4b1'
down_revision = 'f047ca1e2c74'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('solicitacao_acesso', schema=None) as batch_op:
        batch_op.add_column(sa.Column('nome', sa.String(length=100), nullable=False))
        batch_op.add_column(sa.Column('sobrenome', sa.String(length=100), nullable=False))
        batch_op.drop_column('nome_completo')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('solicitacao_acesso', schema=None) as batch_op:
        batch_op.add_column(sa.Column('nome_completo', sa.VARCHAR(length=200), autoincrement=False, nullable=False))
        batch_op.drop_column('sobrenome')
        batch_op.drop_column('nome')

    # ### end Alembic commands ###
