"""Adiciona tabela de solicitacao de acesso

Revision ID: f047ca1e2c74
Revises: 6ab34685a049
Create Date: 2025-08-17 11:35:12.532616

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f047ca1e2c74'
down_revision = '6ab34685a049'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('solicitacao_acesso',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome_completo', sa.String(length=200), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('justificativa', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('Pendente', 'Aprovada', 'Rejeitada', name='status_solicitacao_enum'), nullable=False),
    sa.Column('data_solicitacao', sa.DateTime(), nullable=False),
    sa.Column('admin_id', sa.Integer(), nullable=True),
    sa.Column('data_decisao', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['admin_id'], ['usuario.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('solicitacao_acesso')
    # ### end Alembic commands ###
